kind: Deployment
apiVersion: apps/v1
metadata:
  name: zafin-poc
  labels:
    app: zafin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zafin
  template:
    metadata:
      labels:
        app: zafin
    spec:
      containers:
        - name: zafin-poc
          image: us.icr.io/zcloud-gs-test/zafincore:v2
          env:
          - name: PG_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres
                key: PG_USER
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: PG_PASSWORD
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: postgres
                key: PG_INSTANCE
          volumeMounts:
          - name: postgres 
            mountPath: "/deployments/config" 
            readOnly: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      volumes:
        - name: postgres
          configMap:
            name: postgres 
            items:
             - key: application.properties 
               path: application.properties                 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
